spring:
  application:
    name: library-alexandria
  datasource:
    initialization-mode: always
    url: jdbc:h2:mem:library;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;
    username: sa
#    password: pswd
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: false
      hibernate:
        ddl-auto: create-update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always