spring:
  application:
    name: library-alexandria
  datasource:
    url: jdbc:h2:mem:library;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true
#      hibernate:
#        ddl-auto: none
  h2:
    console.enabled: true
  sql:
    init:
      mode: always