CREATE TABLE AUTHORS (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE WORKS (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE VARCHAR(250) NOT NULL,
    PUBLISHED DATE NOT NULL,
    RARE BOOLEAN DEFAULT FALSE
);

CREATE TABLE AUTHOR_WORK_XREF (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    WORK_ID INT,
    AUTHOR_ID INT,
    FOREIGN KEY (WORK_ID) REFERENCES WORKS(ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID)
);

CREATE TABLE FORMATS (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    WORK_ID INT,
    FORMAT SMALLINT,
    SHIPPING_COST DECIMAL(10, 2)
);

CREATE TABLE FORWARDS (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    WORK_ID INT,
    AUTHOR VARCHAR(100),
    FORWARD LONGTEXT
);

CREATE TABLE VOLUMES (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    WORK_ID INT,
    VOLUME_NUMBER INT,
    SERIES_TITLE VARCHAR(100)
);
